export const LIST_CONTACTS_LOADING = "LIST_CONTACTS_LOADING"
export const LIST_CONTACTS_SUCCESS = "LIST_CONTACTS_SUCCESS"
export const LIST_CONTACTS_FAILURE = "LIST_CONTACTS_FAILURE"

export const CONTACT_LOADING = "CONTACT_LOADING"
export const CONTACT_SUCCESS = "CONTACT_SUCCESS"
export const CONTACT_FAILURE = "CONTACT_FAILURE"
export const CONTACT_CLEAR = "CONTACT_CLEAR"

export const ADD_CONTACT_LOADING = "ADD_CONTACT_LOADING"
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS"
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE"

export const REMOVE_CONTACT_LOADING = "REMOVE_CONTACT_LOADING"
export const REMOVE_CONTACT_SUCCESS = "REMOVE_CONTACT_SUCCESS"
export const REMOVE_CONTACT_FAILURE = "REMOVE_CONTACT_FAILURE"

export const UPDATE_CONTACT_LOADING = "UPDATE_CONTACT_LOADING"
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS"
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE"